include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/core/models/*.g.dart

linter:
  rules:
    avoid_print: false
    sort_child_properties_last: false
    prefer_if_elements_to_conditional_expressions: false