include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    sort_child_properties_last: false
    avoid_positional_boolean_parameters: false
    avoid_classes_with_only_static_members: false
    avoid_function_literals_in_foreach_calls: false