name: sahayatri
description: A virtual travel companion.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utils
  dio: ^4.0.6
  intl: ^0.17.0
  timeago: ^3.3.0
  url_launcher: ^6.1.5
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  device_preview: ^1.1.0
  form_field_validator: ^1.1.0

  # Alert
  flutter_local_notifications: ^9.9.0

  # State Management
  get_it: ^7.2.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1

  # Database
  hive: ^2.2.3

  # Map
  flutter_map: ^2.2.0
  maps_toolkit: ^2.0.1

  # Tracker
  location: ^4.4.0
  nearby_connections: ^3.2.0

  # Translate
  translator: ^0.1.7
  flutter_tts: ^3.3.3

  # Widgets
  animator: ^3.2.0
  fl_chart: ^0.55.1
  photo_view: ^0.14.0
  card_swiper: ^2.0.4
  timeline_tile: ^2.0.0
  sliding_up_panel: ^2.0.0
  loading_indicator: ^3.1.0
  another_flushbar: ^1.10.29
  flutter_rating_bar: ^4.0.1
  flutter_zoom_drawer: ^3.0.3
  community_material_icon: ^5.9.55
  sleek_circular_slider: ^2.0.1
  flutter_staggered_grid_view: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  flutter_native_splash: ^2.2.8
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "36C7CB"
  image: assets/icons/splash.png

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/icons/
    - assets/images/
    - assets/images/markers/
    - assets/images/indicators/
    - assets/images/backgrounds/

  fonts:
    - family: Bozon
      fonts:
        - asset: assets/fonts/Bozon-Bold.otf
          weight: 700
        - asset: assets/fonts/Bozon-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Bozon-Medium.otf
          weight: 500
        - asset: assets/fonts/Bozon-Regular.otf
          weight: 400
        - asset: assets/fonts/Bozon-Light.otf

    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlab-Light.ttf
          weight: 300
