name: sahayatri
description: A virtual tour guide.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Misc
  dio: ^3.0.9
  intl: ^0.16.1
  device_preview: ^0.4.4
  flutter_local_notifications: ^1.4.4+1

  # State Management
  equatable: ^1.2.0
  flutter_bloc: ^4.0.0

  # Map
  location: ^3.0.2
  maps_toolkit: ^1.1.0
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: c590ab12edbf5b6fce30b13a42e974c0abadd506
  # flutter_mapbox_navigation: ^0.0.10

  # Widgets
  animator: ^2.0.0
  fl_chart: ^0.10.0
  photo_view: ^0.9.2
  timeline_tile: ^0.1.2
  auto_size_text: ^2.1.0
  flutter_swiper: ^1.1.6
  sliding_up_panel: ^1.0.2
  flutter_rating_bar: ^3.0.1+1
  loading_indicator_view: ^1.1.0
  flutter_datetime_picker: ^1.3.8
  community_material_icon: ^3.5.95


dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.2.0
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.4


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  image: assets/icon/splash.png
  color: "36C7CB"
  android_disable_fullscreen: true
  

flutter:

  uses-material-design: true

  assets:
    - assets/images/mardi/
    - assets/images/indicators/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen-Regular.ttf
          weight: 500

    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 500
        - asset: assets/fonts/RobotoSlab-Light.ttf
          weight: 300