name: sahayatri
description: A virtual travel companion.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utils
  dio: ^3.0.10
  timeago: ^2.0.29
  url_launcher: ^5.7.10
  path_provider: ^1.6.24
  image_picker: ^0.6.7+14
  intl: ^0.17.0-nullsafety.2
  device_preview: ^0.6.2-beta
  form_field_validator: ^1.0.1

  # Alert
  sms_maintained: ^0.2.5
  flutter_local_notifications: ^3.0.2

  # State Management
  get_it: ^5.0.1
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1

  # Database
  hive: ^1.4.4+1

  # Map
  maps_toolkit: ^1.1.0+2
  flutter_map: ^0.10.1+1

  # Tracker
  location: ^3.1.0
  nearby_connections: ^2.0.2

  # Translate
  translator: ^0.1.5
  flutter_tts: ^2.0.0

  # Widgets
  animator: ^2.0.2
  fl_chart: ^0.12.0
  flushbar: ^1.10.4
  flip_card: ^0.4.4
  photo_view: ^0.10.3
  timeline_tile: ^1.0.0
  flutter_swiper: ^1.1.6
  sliding_up_panel: ^1.0.2
  loading_indicator: ^1.2.0
  flutter_rating_bar: ^3.2.0+1
  flutter_zoom_drawer: ^1.0.4+1
  community_material_icon: ^5.4.55
  sleek_circular_slider: ^1.2.0+web
  flutter_staggered_grid_view: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.5.1
  build_runner: ^1.10.7
  hive_generator: ^0.8.2
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  image: assets/icons/splash.png
  color: "36C7CB"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/markers/
    - assets/images/indicators/
    - assets/images/backgrounds/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen-Regular.ttf
          weight: 500

    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 500
        - asset: assets/fonts/RobotoSlab-Light.ttf
          weight: 300
