name: sahayatri
description: A virtual travel companion.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utils
  dio: ^4.0.4
  intl: ^0.17.0
  image: ^3.1.0
  timeago: ^3.1.0
  url_launcher: ^6.0.17
  path_provider: ^2.0.8
  image_picker: ^0.8.4+4
  device_preview: ^1.0.0
  form_field_validator: ^1.1.0

  # Alert
  flutter_local_notifications: ^9.1.5

  # State Management
  get_it: ^7.2.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0

  # Database
  hive: ^2.0.5

  # Map
  flutter_map: ^0.14.0
  maps_toolkit: ^2.0.0

  # Tracker
  location: ^4.3.0
  nearby_connections: ^3.1.0

  # Translate
  translator: ^0.1.7
  flutter_tts: ^3.2.4

  # Widgets
  animator: ^3.1.0
  fl_chart: ^0.40.6
  photo_view: ^0.13.0
  card_swiper: ^1.0.4
  timeline_tile: ^2.0.0
  sliding_up_panel: ^2.0.0
  loading_indicator: ^3.0.2
  another_flushbar: ^1.10.28
  flutter_rating_bar: ^4.0.0
  flutter_zoom_drawer: ^2.1.2
  community_material_icon: ^5.9.55
  sleek_circular_slider: ^2.0.1
  flutter_staggered_grid_view: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  hive_generator: ^1.1.1
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  image: assets/icons/splash.png
  color: "36C7CB"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/icons/
    - assets/images/
    - assets/images/markers/
    - assets/images/indicators/
    - assets/images/backgrounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlab-Light.ttf
          weight: 300
