name: sahayatri
description: A virtual travel companion.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Misc
  dio: ^3.0.9
  intl: ^0.16.1
  url_launcher: ^5.5.0
  path_provider: ^1.6.11
  image_picker: ^0.6.7+4
  device_preview: ^0.4.7
  form_field_validator: ^1.0.1

  # Notification
  sms_maintained: ^0.2.5
  flutter_local_notifications: ^1.4.4+2

  # State Management
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1

  # Database
  hive: ^1.4.2

  # Map
  location: ^3.0.2
  flutter_map: ^0.10.1+1
  maps_toolkit: ^1.1.0+2

  # Nearby
  nearby_connections: ^1.1.1+1

  # Widgets
  animator: ^2.0.1
  fl_chart: ^0.11.0
  photo_view: ^0.9.2
  flip_card: ^0.4.4
  timeline_tile: ^0.1.2
  auto_size_text: ^2.1.0
  flutter_swiper: ^1.1.6
  sliding_up_panel: ^1.0.2
  loading_indicator: ^1.2.0
  flutter_zoom_drawer: ^1.0.4
  flutter_rating_bar: ^3.0.1+1
  flutter_datetime_picker: ^1.3.8
  community_material_icon: ^5.3.45

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.2.0
  build_runner: ^1.10.2
  hive_generator: ^0.7.1
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5

dependency_overrides:
  build_resolvers: "1.3.10"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  image: assets/icons/splash.png
  color: "36C7CB"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/indicators/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen-Regular.ttf
          weight: 500

    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 500
        - asset: assets/fonts/RobotoSlab-Light.ttf
          weight: 300
