name: sahayatri
description: A virtual travel companion.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utils
  dio: ^5.7.0
  intl: ^0.19.0
  timeago: ^3.7.0
  collection: ^1.18.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  device_preview_plus: ^2.1.5
  form_field_validator: ^1.1.0

  # Alert
  flutter_local_notifications: ^18.0.1

  # State Management
  get_it: ^8.0.2
  provider: ^6.1.2
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6

  # Database
  hive: ^2.2.3

  # Map
  latlong2: ^0.9.1
  maps_toolkit: ^3.0.0
  flutter_map: ^7.0.2

  # Tracker
  location: ^7.0.1
  nearby_connections: ^3.3.0

  # Translate
  translator: ^1.0.3
  flutter_tts: ^4.2.0

  # Widgets
  animator: ^3.3.0
  fl_chart: ^0.69.2
  photo_view: ^0.15.0
  card_swiper: ^3.0.1
  timeline_tile: ^2.0.0
  sliding_up_panel: ^2.0.0
  loading_indicator: ^3.1.1
  another_flushbar: ^1.12.30
  flutter_rating_bar: ^4.0.1
  community_material_icon: ^5.9.55
  sleek_circular_slider: ^2.0.1
  flutter_staggered_grid_view: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: 2.4.12
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1

dependency_overrides:
  pub_semver: 2.1.4
  states_rebuilder: 6.4.0
  watcher: 1.1.0

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/icons/
    - assets/images/
    - assets/images/markers/
    - assets/images/indicators/
    - assets/images/backgrounds/

  fonts:
    - family: Bozon
      fonts:
        - asset: assets/fonts/Bozon-Bold.otf
          weight: 700
        - asset: assets/fonts/Bozon-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Bozon-Medium.otf
          weight: 500
        - asset: assets/fonts/Bozon-Regular.otf
          weight: 400
        - asset: assets/fonts/Bozon-Light.otf

    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlab-Light.ttf
          weight: 300
