import 'package:sahayatri/core/models/language.dart';

class Languages {
  static const Language english = Language(code: 'en', title: 'English');
  static const Language defaultSource = Language(code: 'en', title: 'English');
  static const Language defaultTarget = Language(code: 'ne', title: 'Nepali');
  static const List<Language> all = [
    Language(code: 'auto', title: 'Automatic'),
    Language(code: 'af', title: 'Afrikaans'),
    Language(code: 'sq', title: 'Albanian'),
    Language(code: 'am', title: 'Amharic'),
    Language(code: 'ar', title: 'Arabic'),
    Language(code: 'hy', title: 'Armenian'),
    Language(code: 'az', title: 'Azerbaijani'),
    Language(code: 'eu', title: 'Basque'),
    Language(code: 'be', title: 'Belarusian'),
    Language(code: 'bn', title: 'Bengali'),
    Language(code: 'bs', title: 'Bosnian'),
    Language(code: 'bg', title: 'Bulgarian'),
    Language(code: 'ca', title: 'Catalan'),
    Language(code: 'ceb', title: 'Cebuano'),
    Language(code: 'ny', title: 'Chichewa'),
    Language(code: 'zh-tw', title: 'Chinese'),
    Language(code: 'co', title: 'Corsican'),
    Language(code: 'hr', title: 'Croatian'),
    Language(code: 'cs', title: 'Czech'),
    Language(code: 'da', title: 'Danish'),
    Language(code: 'nl', title: 'Dutch'),
    Language(code: 'en', title: 'English'),
    Language(code: 'eo', title: 'Esperanto'),
    Language(code: 'et', title: 'Estonian'),
    Language(code: 'tl', title: 'Filipino'),
    Language(code: 'fi', title: 'Finnish'),
    Language(code: 'fr', title: 'French'),
    Language(code: 'fy', title: 'Frisian'),
    Language(code: 'gl', title: 'Galician'),
    Language(code: 'ka', title: 'Georgian'),
    Language(code: 'de', title: 'German'),
    Language(code: 'el', title: 'Greek'),
    Language(code: 'gu', title: 'Gujarati'),
    Language(code: 'ht', title: 'Haitian Creole'),
    Language(code: 'ha', title: 'Hausa'),
    Language(code: 'haw', title: 'Hawaiian'),
    Language(code: 'iw', title: 'Hebrew'),
    Language(code: 'hi', title: 'Hindi'),
    Language(code: 'hmn', title: 'Hmong'),
    Language(code: 'hu', title: 'Hungarian'),
    Language(code: 'is', title: 'Icelandic'),
    Language(code: 'ig', title: 'Igbo'),
    Language(code: 'id', title: 'Indonesian'),
    Language(code: 'ga', title: 'Irish'),
    Language(code: 'it', title: 'Italian'),
    Language(code: 'ja', title: 'Japanese'),
    Language(code: 'jw', title: 'Javanese'),
    Language(code: 'kn', title: 'Kannada'),
    Language(code: 'kk', title: 'Kazakh'),
    Language(code: 'km', title: 'Khmer'),
    Language(code: 'ko', title: 'Korean'),
    Language(code: 'ku', title: 'Kurdish (Kurmanji)'),
    Language(code: 'ky', title: 'Kyrgyz'),
    Language(code: 'lo', title: 'Lao'),
    Language(code: 'la', title: 'Latin'),
    Language(code: 'lv', title: 'Latvian'),
    Language(code: 'lt', title: 'Lithuanian'),
    Language(code: 'lb', title: 'Luxembourgish'),
    Language(code: 'mk', title: 'Macedonian'),
    Language(code: 'mg', title: 'Malagasy'),
    Language(code: 'ms', title: 'Malay'),
    Language(code: 'ml', title: 'Malayalam'),
    Language(code: 'mt', title: 'Maltese'),
    Language(code: 'mi', title: 'Maori'),
    Language(code: 'mr', title: 'Marathi'),
    Language(code: 'mn', title: 'Mongolian'),
    Language(code: 'my', title: 'Myanmar (Burmese)'),
    Language(code: 'ne', title: 'Nepali'),
    Language(code: 'no', title: 'Norwegian'),
    Language(code: 'ps', title: 'Pashto'),
    Language(code: 'fa', title: 'Persian'),
    Language(code: 'pl', title: 'Polish'),
    Language(code: 'pt', title: 'Portuguese'),
    Language(code: 'pa', title: 'Punjabi'),
    Language(code: 'ro', title: 'Romanian'),
    Language(code: 'ru', title: 'Russian'),
    Language(code: 'sm', title: 'Samoan'),
    Language(code: 'gd', title: 'Scots Gaelic'),
    Language(code: 'sr', title: 'Serbian'),
    Language(code: 'st', title: 'Sesotho'),
    Language(code: 'sn', title: 'Shona'),
    Language(code: 'sd', title: 'Sindhi'),
    Language(code: 'si', title: 'Sinhala'),
    Language(code: 'sk', title: 'Slovak'),
    Language(code: 'sl', title: 'Slovenian'),
    Language(code: 'so', title: 'Somali'),
    Language(code: 'es', title: 'Spanish'),
    Language(code: 'su', title: 'Sundanese'),
    Language(code: 'sw', title: 'Swahili'),
    Language(code: 'sv', title: 'Swedish'),
    Language(code: 'tg', title: 'Tajik'),
    Language(code: 'ta', title: 'Tamil'),
    Language(code: 'te', title: 'Telugu'),
    Language(code: 'th', title: 'Thai'),
    Language(code: 'tr', title: 'Turkish'),
    Language(code: 'uk', title: 'Ukrainian'),
    Language(code: 'ur', title: 'Urdu'),
    Language(code: 'uz', title: 'Uzbek'),
    Language(code: 'vi', title: 'Vietnamese'),
    Language(code: 'cy', title: 'Welsh'),
    Language(code: 'xh', title: 'Xhosa'),
    Language(code: 'yi', title: 'Yiddish'),
    Language(code: 'yo', title: 'Yoruba'),
    Language(code: 'zu', title: 'Zulu'),
  ];
}
